# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false
gems:                [jekyll-paginate]

# Setup
title:               Yongjoo Park
# tagline:             ''
description:         'Research Fellow<br/> Computer Science and Engineering<br/> University of Michigan, Ann Arbor<br/>4957 Bob and Betty Beyster<br/> pyongjoo@umich.edu'
url:                 http://yongjoopark.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yongjoo Park
  url:               http://www.yongjoopark.com
  email:             pyongjoo@umich.edu

collections:
  intro:
    output: true
  texts:
    output: true
  publications:
    output: true
  #projects:
  #  output: true
  experiences:
    output: true

# Custom vars
version:             1.0.0
updated:             'May 22 2018'

