# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false
gems:                []

# Setup
title:               Yongjoo Park
# tagline:             ''
description:         'Assistant Professor (from 2020)<br/> Department of Computer Science<br/> University of Illinois at Urbana-Champaign<br/>yongjoo@illinois.edu 
  <br/> <br/> Co-founder <br/>Keebo, Inc. <br/> yongjoo@keebo.ai'
url:                 https://yongjoopark.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yongjoo Park
  url:               https://yongjoopark.com
  email:             yongjoo@illinois.edu

collections:
  intro:
    output: true
  texts:
    output: true
  publications:
    output: true
  #projects:
  #  output: true
  experiences:
    output: true

# Custom vars
version:             1.0.0
updated:             'Jan 30 2020'

